# Generated by Django 5.0.4 on 2025-01-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
