# Generated by Django 5.0.4 on 2025-01-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_allrecordform_user_booktypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='booktypes',
            field=models.CharField(max_length=45),
        ),
    ]
