# Generated by Django 5.0.4 on 2025-01-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_user_booktypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='booktypes',
        ),
    ]
