# Generated by Django 5.0.4 on 2025-01-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_user_booktypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booktypes',
            field=models.CharField(default='', max_length=45),
        ),
    ]
