# Generated by Django 5.0.4 on 2025-01-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_date_user_current_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_date',
            new_name='date',
        ),
    ]
